# Virtual NetworkInformation
name: prod
vpc_cidr: "10.0.0.0/24"
trusted_cidrs: ["104.177.8.104/29"]
aws_region: "us-west-1"
aws_az_count: 2
aws_availability_zones: ["us-west-1a", "us-west-1c"]
tags:
  env: "dev"
  application: "edison-ai"
  uai: "UAI2009648"