name: spectro-core
description: spectro-core
type: add-on
cloudType: all
packs:
  - name: "spectro-proxy"
    registry: Public Repo
    type: "spectro"
    layer: "addon"
    version: "1.0.0"
    values: |
        pack:
          spectrocloud.com/install-priority: "-200"
          content:
            images:
              - gcr.io/spectro-images-public/release/frpc:v1.0.0
              - gcr.io/spectro-images-public/release/frpc-init:v1.0.0
              - docker.io/velero/velero:v1.7.1
              - docker.io/velero/velero-plugin-for-aws:v1.3.0

        manifests:
          spectro-proxy:
            namespace: "cluster-{{ .spectro.system.cluster.uid }}"
            server: "{{ .spectro.system.reverseproxy.server }}"
            clusterUid: "{{ .spectro.system.cluster.uid }}"
            subdomain: "cluster-{{ .spectro.system.cluster.uid }}"

  - name: "lb-metallb"
    registry: Public Repo
    type: "spectro"
    layer: "addon"
    version: "0.11.0"
    values: |
        pack:
          spectrocloud.com/install-priority: "0"
          content:
            images:
              - quay.io/metallb/controller:v0.11.0
              - quay.io/metallb/speaker:v0.11.0
        manifests:
          metallb:
            #The namespace to use for deploying MetalLB
            namespace: "metallb-system"
            #MetalLB will skip setting .0 & .255 IP address when this flag is enabled
            avoidBuggyIps: true
            # Layer 2 config; The IP address range MetalLB should use while assigning IP's for svc type LoadBalancer
            # For the supported formats, check https://metallb.universe.tf/configuration/#layer-2-configuration
            addresses:
              - 192.168.100.245-192.168.100.254