name: addon-profile-1
description: addon-profile-1
type: add-on

packs:
  - name: "kubevious-test"
    type: "helm"
    layer: "addon"
    #registryUid: "61eef3db38f78bda90792555"
    registryName: "spectro-helm-repo"
    uid: ""
    version: "0.8.15"
    values: |
      pack:
        namespace: "helm-test-chart"
        spectrocloud.com/install-priority: "230"
        releaseNameOverride:
          test-chart-service: test-chart-service-name