name: profile_infra
description: profile_infra
type: add-on
defaultRepoURL: "${REPO_URL}"
packs:
  - name: install-application
    type: manifest
    manifests:
      - name: install-app-crd
        content: |
          apiVersion: ehl.ees/v1
          kind: ProfileInstallation
          metadata:
            name: "%PROFILE_NAME%"
          spec:
            name: "%PROFILE_SPEC_NAME%"
    values: |
      pack:
        spectrocloud.com/install-priority: "320"
      
      
      622a58174a85b30ed2a9875a