name: tke-dev
cloudType: tke
cloud_account: "tencent-account-tf-simyam"
profiles:
  infra:
    name: profile_infra_tke_simyam
  addons:
    - name: addon-profile-tke-tf1
cloud_config:
  tke_region: ap-mumbai
  tke_vpc_id: vpc-hpzmtrp0
  endpoint_access: private
  tke_subnets:
    us-east-1a: subnet-0931c5e4f56d3,subnet-0c494a15916ac3c
    us-east-1b: subnet-022297ad=0f29,subnet-0a75634ca45df8f
node_groups:
  - name: worker-basic
    count: 3
    disk_size_gb: 61
    instance_type: t3.large
    worker_subnets:
      us-east-1a: subnet-0dac5b9c4d0d5c
      us-east-1b: subnet-0d710ba055568b
backup_policy:
  schedule: "0 0 * * SUN"
  backup_location: qa-sharma
  prefix: weekly
scan_policy:
  configuration_scan_schedule: "0 0 * * SUN"
  penetration_scan_schedule: "0 0 * * SUN"
  conformance_scan_schedule: "0 0 1 * *"