name: tke-dev
cloudType: tke
cloud_account: "tencent-account-tf-simyam"
profiles:
  infra:
    name: profile_infra_tke_simyam
#  addons:
#    - name: addon-profile-tke-tf1
cloud_config:
  tke_region: ap-mumbai
  tke_vpc_id: vpc-hpzmtrp0
  public_access_cidrs: ["0.0.0.0/0"]
  endpoint_access: public
  tke_subnets:
    210001: "subnet-3e3swkyt"
    #"210002" = "210002"

cluster_rbac_binding:
  - type: "ClusterRoleBinding"
    role:
      kind: "ClusterRole"
      name: "testRole3"
    subjects:
      - type: "User"
        name: "testRoleUser3"
      - type: "Group"
        name: "testRoleGroup3"
      - type: "ServiceAccount"
        name: "testrolesubject3"
        namespace: "testrolenamespace"
  - type: "RoleBinding"
    namespace: "test5ns"
    role:
      kind: "Role"
      name: "testRoleFromNS3"
    subjects:
      - type: "User"
        name: "testUserRoleFromNS3"
      - type: "Group"
        name: "testGroupFromNS3"
      - type: "ServiceAccount"
        name: "testrolesubject3"
        namespace: "testrolenamespace"

namespaces:
  - name: "test5ns"
    resource_allocation:
      cpu_cores: "2"
      memory_MiB: "2048"

node_groups:
  - name: worker-basic
    count: 1
    disk_size_gb: 30
    instance_type: "S3.MEDIUM4"
    worker_subnets:
      210001: "subnet-3e3swkyt"
      #"210002" = "210002"

    additional_labels:
      addlabel: "addlabelval1"

    taints:
      - key: "taintkey1"
        value: "taintvalue1"
        effect: "PreferNoSchedule"
      - key: "taintkey2"
        value: "taintvalue2"
        effect: "NoSchedule"