name: profile_infra_tke_simyam
description: profile_infra
cloudType: tke
type: cluster
defaultRepoURL: "${REPO_URL}"
packs:
  - name: "ubuntu-tke"
    registry: Public Repo
    type: "spectro"
    layer: "os"
    server: "${SPECTRO_REPO_URL}"
    version: "18.04"
    values: |
      pack:
        # Defaults to TKE image for Ubuntu Server 18.04.1 LTS 64bit
        # To use other images supported by TKE, execute `tccli tke DescribeImages` and provide a valid OsName value below
        tencentManagedOSName: "ubuntu18.04.1x86_64"
  - name: "kubernetes-tke"
    registry: Public Repo
    type: "spectro"
    layer: "k8s"
    server: "${SPECTRO_REPO_URL}"
    version: "1.20.6"
    values: |
      ## TKE kubernetes values
  - name: "cni-tke-global-router"
    registry: Public Repo
    layer: "cni"
    server: "${SPECTRO_REPO_URL}"
    type: "spectro"
    values: "# TKE Global Router CNI will be auto-installed"
    version: "1.0"
  - name: "csi-tke"
    registry: Public Repo
    layer: "csi"
    server: "${SPECTRO_REPO_URL}"
    type: "spectro"
    version: "1.0"
    values: |
      manifests:
        storageclass:
          #Supported binding modes are Immediate, WaitForFirstConsumer
          #Set this to WaitForFirstConsumer, so that the volumes gets created in the same AZ as that of the pods
          volumeBindingMode: "WaitForFirstConsumer"

          #Flag to denote if this should be the default storage class for dynamic provisioning
          isDefaultClass: "true"

          allowVolumeExpansion: true

          parameters:
            diskType: CLOUD_BASIC
            diskChargeType: PREPAID
            diskChargeTypePrepaidPeriod: "2"
            diskChargePrepaidRenewFlag: NOTIFY_AND_AUTO_RENEW